# Generated by Django 4.2.29 on 2026-03-30 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('drives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('round_name', models.CharField(choices=[('written', 'Written'), ('gd', 'Group Discussion'), ('technical', 'Technical'), ('hr', 'HR')], max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='drives.placementdrive')),
            ],
        ),
        migrations.CreateModel(
            name='RoundResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='applications.driveround')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_results', to='students.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DriveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('current_round', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='drives.placementdrive')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='students.studentprofile')),
            ],
        ),
    ]
