# Generated by Django 5.0.6 on 2026-03-31 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('logo', models.URLField(blank=True, max_length=500, null=True)),
                ('naac_grade', models.CharField(blank=True, max_length=10, null=True)),
                ('established_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.college'),
        ),
    ]
