# Generated by Django 4.2.29 on 2026-03-30 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('drives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounds_description', models.TextField()),
                ('questions_asked', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('tips', models.TextField(blank=True, null=True)),
                ('overall_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='drives.placementdrive')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='students.studentprofile')),
            ],
        ),
    ]
