# Generated by Django 4.2.29 on 2026-03-30 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=255)),
                ('role_name', models.CharField(max_length=255)),
                ('ctc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eligibility_gpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('eligible_branches', models.JSONField(default=list)),
                ('max_backlogs', models.IntegerField(default=0)),
                ('drive_date', models.DateField()),
                ('registration_deadline', models.DateTimeField()),
                ('job_location', models.CharField(max_length=255)),
                ('rounds_count', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drives', to='companies.company')),
            ],
        ),
    ]
