# Generated by Django 5.0.6 on 2026-03-31 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_college_user_college'),
        ('drives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementdrive',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drives', to='accounts.college'),
        ),
        migrations.AlterField(
            model_name='placementdrive',
            name='college_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
