# Generated by Django 4.2.29 on 2026-03-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='employee_count',
            field=models.CharField(blank=True, choices=[('<100', 'Less than 100'), ('100-1000', '100 – 1,000'), ('1000-10000', '1,000 – 10,000'), ('10000+', 'More than 10,000')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, choices=[('IT', 'IT / Software'), ('Finance', 'Finance / Banking'), ('Core', 'Core Engineering'), ('Consulting', 'Consulting'), ('Other', 'Other')], max_length=150, null=True),
        ),
    ]
